version: 2
jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/photolens
    docker:
      - image: circleci/python:3.5.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DJANGO_SETTINGS_MODULE: api.settings
      - image: circleci/postgres:9.6.2 # an example of how to specify a service container
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout  # checkout source code to working directory
      - run:
        command: |  # use pipenv to install dependencies
          sudo pip install pipenv
          pipenv install

